<?php

namespace Tests\Feature\Security;

use App\Models\Character;
use App\Models\Combo;
use App\Models\Game;
use App\Models\GameEntry;
use App\Models\ListModel;
use App\Models\ListPage;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * End-to-end stored XSS: hostile content goes in through the real submission
 * route and comes back out of the real page, so these cover the rendering
 * layer as it is actually assembled rather than a service in isolation.
 *
 * The app currently has only twelve {!! !!} sites and every one of them is
 * either nl2br(e(...)), a json_encode into a <script type="application/json">
 * island, or generated by ComboNotationRenderer. That is the present state of
 * the code, not an enforced invariant — nothing stops the next unescaped
 * interpolation, which is what these are for.
 */
class StoredXssTest extends TestCase
{
    use RefreshDatabase;

    private Game $game;

    private Character $character;

    private GameEntry $listingType;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp();

        $this->game = Game::create(['name' => 'Test Game', 'complete' => 1, 'modPass' => 'secret']);
        $this->character = Character::create(['name' => 'Fighter', 'game_idgame' => $this->game->idgame]);
        $this->listingType = GameEntry::create(['title' => 'Combo', 'gameid' => $this->game->idgame, 'order' => 1]);
        $this->user = User::create(['nickname' => 'submitter', 'password' => 'password123']);

        $this->actingAs($this->user);
    }

    private function submitCombo(array $overrides = []): Combo
    {
        $this->post(route('games.combos.store', $this->game), array_merge([
            'combo' => '5LP > 5MP',
            'character_idcharacter' => $this->character->idcharacter,
            'listingtype' => $this->listingType->entryid,
        ], $overrides))->assertRedirect();

        return Combo::latest('idcombo')->sole();
    }

    /**
     * Covers all three notation {!! !!} sites on the combo page at once,
     * since they all render the same submitted string.
     */
    public function test_a_combo_notation_containing_a_script_tag_is_escaped_on_the_combo_page(): void
    {
        $payload = '<script>alert(1)</script>';
        $combo = $this->submitCombo(['combo' => $payload]);

        $response = $this->get(route('combos.show', $combo))->assertOk();

        $response->assertDontSee($payload, false);
        $response->assertSee('&lt;script&gt;', false);
    }

    public function test_an_attribute_breakout_payload_in_a_comment_is_escaped_on_the_combo_page(): void
    {
        $payload = '"><img src=x onerror=alert(1)>';
        $combo = $this->submitCombo(['comments' => $payload]);

        $response = $this->get(route('combos.show', $combo))->assertOk();

        $response->assertDontSee($payload, false);
        $response->assertDontSee('<img src=x onerror=', false);
    }

    public function test_a_javascript_url_in_the_video_field_does_not_become_a_live_embed(): void
    {
        $combo = $this->submitCombo(['video' => 'javascript:alert(1)']);

        $content = $this->get(route('combos.show', $combo))->assertOk()->getContent();

        $this->assertStringNotContainsString('src="javascript:', $content);
        $this->assertStringNotContainsString("src='javascript:", $content);
        $this->assertStringNotContainsString('href="javascript:', $content);
    }

    /**
     * The canvas data is handed to the front end as JSON inside a
     * <script type="application/json"> island. What actually makes that safe
     * is that json_encode escapes forward slashes as \/ by default, so the
     * sequence "</script>" can never appear in the output — this test is the
     * alarm if anyone ever adds JSON_UNESCAPED_SLASHES to those calls.
     */
    public function test_a_canvas_node_title_cannot_break_out_of_the_json_island(): void
    {
        $payload = '</script><img src=x onerror=alert(1)>';

        $list = ListModel::create([
            'list_name' => 'Guide',
            'game_idgame' => $this->game->idgame,
            'password' => 'unused',
            'type' => 1,
            'user_iduser' => $this->user->iduser,
        ]);

        $page = ListPage::create([
            'Title' => 'Canvas',
            'idList' => $list->idlist,
            'page_type' => 'canvas',
        ]);

        $this->postJson(route('lists.manage.canvas.nodes.store', [$list, $page]), [
            'node_type' => 'text',
            'title' => $payload,
            'body' => 'x',
            'pos_x' => 0,
            'pos_y' => 0,
        ])->assertCreated();

        foreach ([
            route('lists.show', $list).'?page='.$page->idListPage,
            route('lists.manage.canvas.edit', [$list, $page]),
        ] as $url) {
            $content = $this->get($url)->assertOk()->getContent();

            $this->assertStringNotContainsString('</script><img', $content, "{$url} let a payload close the script tag");
            $this->assertStringContainsString('<\\/script>', $content, "{$url} stopped escaping slashes in its JSON island");
        }
    }

    public function test_a_hostile_list_name_is_escaped_on_the_list_search_page(): void
    {
        $payload = '<script>alert(1)</script>';

        ListModel::create([
            'list_name' => $payload,
            'game_idgame' => $this->game->idgame,
            'password' => 'unused',
            'type' => 1,
            'user_iduser' => $this->user->iduser,
        ]);

        $response = $this->get(route('lists.search', ['list_name' => 'script']))->assertOk();

        $response->assertDontSee($payload, false);
        $response->assertSee('&lt;script&gt;', false);
    }

    public function test_a_hostile_nickname_is_escaped_wherever_the_user_is_displayed(): void
    {
        $payload = '<script>alert(1)</script>';

        $hostile = User::create(['nickname' => $payload, 'password' => 'password123']);

        $combo = Combo::create([
            'combo' => '5LP > 5MP',
            'character_idcharacter' => $this->character->idcharacter,
            'type' => $this->listingType->entryid,
            'user_iduser' => $hostile->iduser,
            'verified' => true,
        ]);

        foreach ([route('users.show', $hostile), route('combos.show', $combo)] as $url) {
            $response = $this->get($url)->assertOk();

            $response->assertDontSee($payload, false);
        }
    }
}
